[alembic]
script_location = migrations
file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

prepend_sys_path = .

sqlalchemy.url = postgresql+asyncpg://banking_user:banking_pass@db:5432/banking_db

[post_write_hooks]

[logging]
default_level = INFO
